language: rust
cache: cargo
env:
  global:
    - GETTEXT_VERSION=0.19.8.1
matrix:
  include:
    - name: "Non-Bundled"
      env:
        - CARGO_FLAGS=--no-default-features
      addons:
        apt:
          packages:
            - libgpg-error-dev
    - name: "Bundled"
      install:
        - .travis/install-gettext.sh $GETTEXT_VERSION
    - name: "musl libc"
      env:
        - CARGO_FLAGS="--target x86_64-unknown-linux-musl"
        - GETTEXT_VERSION=0.19.8.1
      addons:
        apt:
          packages:
            - musl-tools
      install:
        - rustup target add x86_64-unknown-linux-musl
        - .travis/install-gettext.sh $GETTEXT_VERSION
    - rust: nightly
      env:
        - GETTEXT_VERSION=0.19.8.1
      install:
        - .travis/install-gettext.sh $GETTEXT_VERSION
    - os: osx
      addons:
        homebrew:
          packages:
            # - gettext
            - gnupg
      # install:
      #   - brew link gettext --force
    - os: windows
      env: CARGO_FLAGS="--target x86_64-pc-windows-gnu"
      install:
        - rustup target add x86_64-pc-windows-gnu
        - choco install msys2
        - pacman -Sy base-devel
  allow_failures:
    - rust: nightly
    - os: windows
script:
  - cargo build --verbose --verbose $CARGO_FLAGS
  - cargo test --verbose --no-fail-fast $CARGO_FLAGS
  - cargo run -p systest $CARGO_FLAGS || true
branches:
  except:
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
notifications:
  email:
    on_success: never
