[package]
name = "gpg-error"
version = "0.3.0"
authors = ["John Schug <john.ips.schug@gmail.com>"]
license = "LGPL-2.1"
repository = "https://github.com/johnschug/rust-gpg-error"
documentation = "https://docs.rs/gpg-error"
categories = ["api-bindings"]
keywords = ["gpg"]
description = "Libgpg-error bindings for Rust"
build = "build.rs"

[dependencies.libgpg-error-sys]
path = "libgpg-error-sys"
version = "0.3.0"

[workspace]
