[package]
name = "gpg-error"
description = "Libgpg-error bindings for Rust"
repository = "https://github.com/johnschug/rust-gpg-error"
documentation = "https://johnschug.github.io/rust-gpg-error"
version = "0.1.4"
authors = ["John Schug <john.ips.schug@gmail.com>"]
license = "LGPL-2.1"
keywords = ["gpg"]

[dependencies.libgpg-error-sys]
path = "libgpg-error-sys"
version = "0.1.2"
